### ISSUE TITLE
OpenSSL broken on iOS 8.1 and Swift (Xcode 6.1.1)

### ISSUE THREAD

**Issue by bbsan2k** [FredericJacobs/OpenSSL-Pod#10]
Hi,

Currently trying to get your pod to work in a Swift project.
Actually it installs through cocoapods, but when I try to include it, there are some Errors.

To reproduce:
- Create ne Swift only Project
- Use latest pod on cocoapods 0.3.6.rc.1
- Include <openssl/aes.h> in bridging header

Looks like there are some headers missing.

**Comment by FredericJacobs** [comment]
I'm not working with Swift currently and have a lot of things to take care of.
Happy to review a PR but not planning to write one.

**Comment by dapperstout** [comment]
I also couldn't get OpenSSL to work with cocoapods 0.3.6.rc.1 in a Swift project. I tried to modify the podspec in this repo, but failed. Eventually I created a new podspec that uses the OpenSSL-for-iOS scripts from @x2on. 

You can find the new Pod here: http://cocoapods.org/?q=openssl-framework

**Comment by FredericJacobs** [comment]
Thanks but using precompiled libraries seems unacceptable for any open source security related projects. I'll give it a look soon and submit a PR to CocoaPods if there is something that needs to be addressed on their end.

**Comment by dapperstout** [comment]
It actually isn't precompiled. The OpenSSL sources will be compiled when you do a 'pod install'.

**Comment by bbsan2k** [comment]
Actually the problems seems to be at another location. Initially I thought I need to include openssl in my bridging Headers, but as it turns out, cocoapods builds framworks for all pods with ("use_frameworks!
") Flag.
The Problems seems to be, that cocoapods tries to build the Framework and actually manages to do so, but the moment you try to import it in a swift file, there are linker errors

The Errors are in:
dtls1.h: 142, 253, 254
rc2.h:78
...

@FredericJacobs I actually think you are right and it's a cocoapods issue
@dapperstout s Solution works for building openssl with cocoapods, but cocoapods fails to integrate the Framework because it wasn't built automatically using their umbrella header system

**Comment by dapperstout** [comment]
@bbsan2k You are right, the OpenSSL-Framework pod doesn't include an umbrella header, so you cannot directly import openssl into your swift files. I'm using the OpenSSL-Framework pod in a combined swift-objc project, where I only import OpenSSL stuff in the objc sources.

**Comment by bbsan2k** [comment]
As a matter of fact, this issue seems to be related to https://github.com/CocoaPods/CocoaPods/issues/3499

**Comment by FredericJacobs** [comment]
Was this resolved by CocoaPods updates?
