### ISSUE TITLE
OpenSSL 1.0.2 tarball has disappeared

### ISSUE THREAD

**Issue by postmechanical** [FredericJacobs/OpenSSL-Pod#11]
Installing OpenSSL (1.0.200)

	[!] Error installing OpenSSL
	[!] /usr/bin/curl -f -L -o /Users/distiller/lpm-mmd-ios/Pods/OpenSSL/file.tgz "https://www.openssl.org/source/openssl-1.0.2.tar.gz" --create-dirs

	  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

									 Dload  Upload   Total   Spent    Left  Speed

	  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0

	curl: (22) The requested URL returned error: 404 Not Found

	pod install returned exit code 1

	Action failed: pod install

**Comment by voznesenskym** [comment]
Ditto, Here it is with --verbose 

-> Installing OpenSSL (1.0.200)
 > Http download
   $ /opt/local/bin/curl -f -L -o /Users/michael/Desktop/opensource/Signal-iOS/Pods/OpenSSL/file.tgz
   "https://www.openssl.org/source/openssl-1.0.2.tar.gz" --create-dirs
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (22) The requested URL returned error: 404 Not Found

[!] Error installing OpenSSL
[!] /opt/local/bin/curl -f -L -o /Users/michael/Desktop/opensource/Signal-iOS/Pods/OpenSSL/file.tgz "https://www.openssl.org/source/openssl-1.0.2.tar.gz" --create-dirs

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (22) The requested URL returned error: 404 Not Found

**Comment by FredericJacobs** [comment]
Currently working on 1.0.2a support.

**Comment by voznesenskym** [comment]
Anything I can do to help?

**Comment by FredericJacobs** [comment]
Added!

**Comment by Xorosho** [comment]
have the same problem, there is no file by this link (https://www.openssl.org/source/openssl-1.0.2.tar.gz)
