### ISSUE TITLE
Enable Bitcode

### ISSUE THREAD

**Issue by tuoxie007** [FredericJacobs/OpenSSL-Pod#23]

**Comment by rafcabezas** [comment]
I second this request.

**Comment by FredericJacobs** [comment]
[## BitNope](https://medium.com/@FredericJacobs/why-i-m-not-enabling-bitcode-f35cd8fbfcc5)

**Comment by rafcabezas** [comment]
I have to admit your abrupt closure of the issue seemed rude at first, but after reading your post I have to agree that the upside to bitcode is probably not worth all the implications.
