### ISSUE TITLE
Issue Installing OpenSSL (1.0.204.1)

### ISSUE THREAD

**Issue by dmi3j** [FredericJacobs/OpenSSL-Pod#26]
Unable to install pod version 1.0.204.1 

```
$ pod --version && pod repo update && pod install
0.39.0
Updating spec repo `master`
Already up-to-date.
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Installing OpenSSL (1.0.204.1)

[!] Error installing OpenSSL
[!] /usr/bin/curl -f -L -o /var/folders/lt/1zypd7251rbg9qdygfq2xx2w0000gn/T/d20151204-86704-ezv5l9/file.tgz https://openssl.org/source/openssl-1.0.2d.tar.gz --create-dirs

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (22) The requested URL returned error: 404 Not Found
```

**Comment by FredericJacobs** [comment]
Please use 1.0.205, 1.0.204.1 was pulled for security reasons.
https://www.openssl.org/news/secadv/20151203.txt

**Comment by AdrianaPineda** [comment]
Hi! 
I changed to 1.0.205 but I'm still getting the 404 error with this URL https://openssl.org/source/openssl-1.0.2e.tar.gz

**Comment by FredericJacobs** [comment]
@AdrianaPineda : OpenSSL just updated. Pod update should fix your issue!

**Comment by AdrianaPineda** [comment]
@FredericJacobs awesome! Is working now. Thanks!

**Comment by swinghu** [comment]
[!] Error installing OpenSSL
[!] /usr/bin/curl -f -L -o /var/folders/gg/3xhhqth56rzctt883bbmys300000gn/T/d20160216-1916-17oezve/file.tgz https://openssl.org/source/openssl-1.0.2e.tar.gz --create-dirs

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0curl: (22) The requested URL returned error: 404 Not Found

now,1.0.205 should change to 1.0.206?

**Comment by swinghu** [comment]
Yes ,now should use 1.0.206,thanks
