### ISSUE TITLE
Error installing OpenSSL (1.0.205)

### ISSUE THREAD

**Issue by SwiftArchitect** [FredericJacobs/OpenSSL-Pod#28]
<pre>
Installing OpenSSL (1.0.205)

[!] Error installing OpenSSL
[!] /usr/bin/curl -f -L -o /var/folders/vl/q8v6pm857859gkyq1kxn1l09ffx3ct/T/d20160128-10254-12eil9y/file.tgz https://openssl.org/source/openssl-1.0.2e.tar.gz --create-dirs

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (22) The requested URL returned error: 404 Not Found

</pre>

**Comment by FredericJacobs** [comment]
Fixed by #27
