### ISSUE TITLE
versions 1.0.200 - 1.0.207 have invalid paths to sources

### ISSUE THREAD

**Issue by userow** [FredericJacobs/OpenSSL-Pod#37]
It gives out 404 when downloading non-last (1.0.208 for now) version.

-    "http": "https://openssl.org/source/openssl-1.0.2a.tar.gz",
+    "http": "https://openssl.org/source/old/1.0.2/openssl-1.0.2a.tar.gz",

through

-    "http": "https://openssl.org/source/openssl-1.0.2g.tar.gz",
+    "http": "https://openssl.org/source/old/1.0.2/openssl-1.0.2g.tar.gz",

**Comment by FredericJacobs** [comment]
This was a conscious decision to prevent people from using deprecated (and likely vulnerable) OpenSSL versions.

**Comment by userow** [comment]
Actually, the only reason why I was using 1.0.207 in my project was the fact that 1.0.208 was not assembling after downloading through CocoaPods.

1.0.207 was assembling. 1.0.200 through 1.0.203 have correct paths in CocoaPod's Specs. 

So.. YES, by not giving out  pre-last version's correct path you are forcing users to use 1.0.208. ... OR ... 1.0.203.
